### ISSUE TITLE
Feature: User can sign up and login to account

### ISSUE THREAD

**Issue by leejaejoseph** [leejaejoseph/final-project-lfz#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign up and login to account
## 📐 Functionality

The user will be introduced to the welcome page where they can either signup or login.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/116613246/220240371-4d7150c9-a1a6-4028-a511-53b49bb840fc.png)
![image](https://user-images.githubusercontent.com/116613246/220240440-3cc3785c-69d8-41ed-8cfb-535bd084d68d.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to ... create table of user names.
- [ ] Update `data.sql` to ... users storing username and hashed password

### ☁️ Server Tasks

- [ ] Update `server/index.js` to ... take username and password and post it into the sql
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a component to ... hash the password when signed up
- [ ] Create a component to ... take the login information
- [ ] Update component to ... give client confirmation permissions

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] add blur and cursor tracking blob
- [ ] Make navbar for mobile
  - [ ] Add the correct anchors for the different tabs 
  - [ ] make the navbar for desktop
- [ ] Add page content to fade in per text content. 
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
